#if !canImport(ObjectiveC)
import XCTest

extension XMLDecodeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLDecodeTests = [
        ("testDocument", testDocument),
        ("testElement", testElement),
        ("testElementChildren", testElementChildren),
        ("testSelfElement", testSelfElement),
        ("testSelfElementAttributes", testSelfElementAttributes),
        ("testTextElement", testTextElement),
        ("testTextElementAttributes", testTextElementAttributes),
        ("testUppercasedHeader", testUppercasedHeader),
    ]
}

extension XMLEncodeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLEncodeTests = [
        ("testDocument", testDocument),
        ("testElement", testElement),
        ("testElementChildren", testElementChildren),
        ("testSelfElement", testSelfElement),
        ("testSelfElementAttributes", testSelfElementAttributes),
        ("testTextElement", testTextElement),
        ("testTextElementAttributes", testTextElementAttributes),
    ]
}

extension XMLStringTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLStringTests = [
        ("testAttributes", testAttributes),
        ("testCrazyChildrens", testCrazyChildrens),
        ("testDocument", testDocument),
        ("testElement", testElement),
        ("testElementChildren", testElementChildren),
        ("testElementChildrens", testElementChildrens),
        ("testTextChildren", testTextChildren),
    ]
}

extension XMLTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLTests = [
        ("testDocument", testDocument),
        ("testElement", testElement),
        ("testElementChildren", testElementChildren),
        ("testElementNode", testElementNode),
        ("testNodeValue", testNodeValue),
        ("testTextNode", testTextNode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XMLDecodeTests.__allTests__XMLDecodeTests),
        testCase(XMLEncodeTests.__allTests__XMLEncodeTests),
        testCase(XMLStringTests.__allTests__XMLStringTests),
        testCase(XMLTests.__allTests__XMLTests),
    ]
}
#endif
